/* **********************************************************
 * Copyright 2003 VMware, Inc. All rights reserved. -- VMware Confidential
 * **********************************************************/

/*
 * Table of system calls, to be included as needed (typically twice:
 * for the enum declaration, and for a string table for printing).
 * 
 * Usage: * VMNIX_VMK_CALL(vmnix name, vmkernel handler, argc, arg1 type, arg1 name, ...)
 *  vmkernel handler:  handler in the vmkernel for this syscall
 *  vmnix name:        Name used in the vmnix module to make this syscall. 
 *                     An '_' is automatically prepended.
 *  number of args:    Number of arguments.
 *  arg1 type:         The type of argument 1
 *  arg1 name:         name of argument 1
 *  etc.
 */

VMNIX_VMK_CALL(Idle, Host_Idle, 0)
VMNIX_VMK_CALL(RpcRegister, Host_RPCRegister, 3, char *, name, int, nameLength, RPC_Connection *, cnxID)
VMNIX_VMK_CALL(RpcUnregister, Host_RPCUnregister, 2, RPC_Connection, cnxID, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(GetMsg, Host_RPCGetMsg, 2, RPC_Connection, cnxID, RPC_MsgInfo *, msgInfo)
VMNIX_VMK_CALL(SendReply, Host_RPCPostReply, 4, RPC_Connection, cnxID, RPC_Token, token, void *, data, unsigned int, length)
VMNIX_VMK_CALL(CheckPendingMessages, RPC_CheckPendingMsgs, 1, RPC_CnxList *, cnxList)
VMNIX_VMK_CALL(CreateWorld, Host_CreateWorld, 1, VMnix_CreateWorldArgs *, args)
VMNIX_VMK_CALL(BindWorld, Host_BindWorld, 3, World_ID, worldID, uint32, vcpuid, World_ID *, hostWorldID)
VMNIX_VMK_CALL(DestroyWorld, Host_DestroyWorld, 1, World_ID, worldID)
VMNIX_VMK_CALL(AddPage, World_AddPage, 4, World_ID, worldID, unsigned long, vpn, unsigned long, mpn, int, readOnly)
VMNIX_VMK_CALL(WorldExists, World_Exists, 1, World_ID, worldID)
VMNIX_VMK_CALL(PageFault, Alloc_COSPhysPageFault, 3, World_ID, worldID, unsigned long, ppn, MPN *, mpn)
VMNIX_VMK_CALL(OvhdPageFault, Alloc_OvhdPageFault, 3, World_ID, worldID, unsigned long, vpn, MPN *, mpn)
VMNIX_VMK_CALL(SendMsg, Host_RPCSendMsg, 4, RPC_Connection, cnxID, int32, function, char *, data, uint32, dataLength)
VMNIX_VMK_CALL(SCSIGetCapacity, HostSCSIGetCapacity, 2, SCSI_HandleID *, handleID, VMnix_GetCapacityResult *, result)
VMNIX_VMK_CALL(NetInfo, HostNetInfo, 2, int, cmd, VMnix_NetInfoArgs *, args)
VMNIX_VMK_CALL(TargetInfo, HostTargetInfo, 3, VMnix_TargetInfoArgs *, args, VMnix_TargetInfo *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(ProcRead, Proc_HandleRead, 2, int, entryNum, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(ProcWrite, Proc_HandleWrite, 2, int, entryNum, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(SCSICommand, HostSCSICommand, 2, SCSI_HandleID *, handleID, HostSCSI_Command *, command)
VMNIX_VMK_CALL(SCSICmdComplete, HostSCSICmdComplete, 3, SCSI_HandleID *, handleID, SCSI_Result *, outResult, Bool *, more)
VMNIX_VMK_CALL(VmkWarning, HostWarning, 2, char *, string, int, length)
VMNIX_VMK_CALL(NetConnect, Net_HostConnect, 2, VMnix_NetConnectArgs *, args, Net_PortID *, portID)
VMNIX_VMK_CALL(NetDisconnect, Net_HostDisconnect, 2, World_ID, worldID, Net_PortID, portID)
VMNIX_VMK_CALL(NetPortEnable, HostNetPortEnable, 2, VMnix_NetPortEnableArgs *, args, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(NetPortDisable, HostNetPortDisable, 2, VMnix_NetPortDisableArgs *, args, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(NetTx, Net_HostTx, 1, Net_PortID , portID)
VMNIX_VMK_CALL(NetUpdateEthFRP, Net_HostUpdateEthFRP, 1, Net_PortID , portID)
VMNIX_VMK_CALL(ModLoadProbe, Mod_LoadProbe, 1, int, moduleID)
VMNIX_VMK_CALL(FilePhysMemIO, HostFilePhysMemIO, 2, VMnix_FilePhysMemIOArgs *, args, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(DisableHostInterrupt, HostDisableInterrupt, 1, IRQ, irq)
VMNIX_VMK_CALL(HelperRequestStatus, HostHelperRequestStatus, 1, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FindAdapName, HostFindAdapName, 3,  uint16, bus, uint16, devfn, char *, name)
VMNIX_VMK_CALL(BlockCommand, HostBlockCommand, 2, SCSI_HandleID *, handleID, HostSCSI_Command *, command)
VMNIX_VMK_CALL(POSTStart, POST_Start, 0)
VMNIX_VMK_CALL(POSTIsDone, POST_IsDone, 0)
VMNIX_VMK_CALL(AllocVMKMem, HostAllocVMKMem, 2, uint32 *, size, void **, vaddr)
VMNIX_VMK_CALL(FreeVMKMem, HostFreeVMKMem, 1, void *, vaddr)
VMNIX_VMK_CALL(SCSIGetGeometry, HostSCSIGetGeometry, 3, SCSI_HandleID *, handleID, VMnix_GetCapacityResult *, result, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(SaveBIOSInfoIDE, HostSaveBIOSInfoIDE, 1, char *, info)
VMNIX_VMK_CALL(EnableHostInterrupt, HostEnableInterrupt, 1, IRQ, irq)
VMNIX_VMK_CALL(PhysMemMap, Alloc_PhysMemMap, 3, World_ID, worldID, uint32, offset, size_t, len)
VMNIX_VMK_CALL(PhysMemUnmap, Alloc_PhysMemUnmap, 3, World_ID, worldID, uint32, offset, size_t, len)
VMNIX_VMK_CALL(ProcRequestUpdate, Proc_UpdateRequested, 0)
VMNIX_VMK_CALL(HelperRequestCancel, HostHelperRequestCancel, 2, Helper_RequestHandle *, helperHandle, Bool, force)
VMNIX_VMK_CALL(SCSIAdapProcInfo, HostSCSIAdapProcInfo, 3, VMnix_ProcArgs*, args, VMnix_ProcResult*, result, Helper_RequestHandle*, hostHelperHandle)
VMNIX_VMK_CALL(GetNICStats, HostGetNICStats, 3, VMnix_NICStatsArgs *, args, void*, result, Helper_RequestHandle*, handle)
VMNIX_VMK_CALL(SCSIDevIoctl, HostSCSIDevIoctl, 3, VMnix_SCSIDevIoctlArgs *, args, VMnix_SCSIDevIoctlResult *, res, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(CharDevIoctl, HostCharDevIoctl, 3, VMnix_CharDevIoctlArgs *, args, VMnix_CharDevIoctlResult *, res, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(NetDevIoctl, HostNetDevIoctl, 3, VMnix_NetDevIoctlArgs *, args, VMnix_NetDevIoctlResult *, res, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(ReadPage, HostReadPage, 3, World_ID, worldID, unsigned long, vpn, char *, pageBuffer)
VMNIX_VMK_CALL(ReadRegs, Host_ReadRegs, 3, World_ID, worldID, char *, buffer, unsigned long, bufferLength)
VMNIX_VMK_CALL(Unload, Host_Unload, 1, int, force)
VMNIX_VMK_CALL(ModAlloc, HostModAlloc, 2, VMnix_ModAllocArgs *, args, VMnix_ModAllocResult *, result)
VMNIX_VMK_CALL(ModPutPage, HostModPutPage, 3, int, moduleID, void *, addr, void *, data)
VMNIX_VMK_CALL(ModLoadDone, HostModLoadDone, 1, VMnix_ModLoadDoneArgs *, args)
VMNIX_VMK_CALL(GetAPICBase, Host_GetAPICBase, 1, MA *, ma)
VMNIX_VMK_CALL(OpenSCSIDev, HostOpenSCSIDevice, 3, VMnix_OpenSCSIDevArgs *, args, VMnix_OpenSCSIDevIntResult *, result, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(CloseSCSIDev, HostCloseSCSIDevice, 3, World_ID, worldID, SCSI_HandleID *, handleID, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FileOpen, HostFileOpen, 3, VMnix_FileOpenArgs *, args, VMnix_FileOpenResult *, result, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(FileClose, HostFileClose, 2, FS_FileHandleID *, handleID, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(ChangeDevOwnership, PCI_ChangeDevOwnership, 1, VMnix_DevArgs *, args)
VMNIX_VMK_CALL(ChangeDevOwnershipProbe, PCI_ChangeDevOwnershipProbe, 1, VMnix_DevArgs *, args)
VMNIX_VMK_CALL(GetDevName, PCI_GetDevName, 1, VMnix_DevArgs *, args)
VMNIX_VMK_CALL(ModUnload, HostModUnload, 2, VMnix_ModUnloadArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(ModList, HostModList, 2, int, numModules, VMnix_ModListResult *, r)
VMNIX_VMK_CALL(LookupMPN, HostLookupMPN, 2, World_ID, worldID, VPN, userVPN)
VMNIX_VMK_CALL(ModAddSym, HostModAddSym, 1, VMnix_SymArgs *, args)
VMNIX_VMK_CALL(ModGetSym, HostModGetSym, 1, VMnix_SymArgs *, args)
VMNIX_VMK_CALL(OpenSerialPort, Serial_OpenPort, 1, unsigned long, port)
VMNIX_VMK_CALL(FSCreate, HostFSCreate, 2, VMnix_FSCreateArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FSToVMFS2, HostFSToVMFS2, 2, VMnix_ConvertToFS2Args *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FSExtend, HostFSExtend, 2, VMnix_FSExtendArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FSGetAttr, HostFSGetAttr, 3, VMnix_FSGetAttrArgs *, args, VMnix_PartitionListResult *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FSSetAttr, HostFSSetAttr, 2, VMnix_FSSetAttrArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FSReaddir, HostFSReaddir, 3, VMnix_ReaddirArgs *, args, VMnix_ReaddirResult *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FSDump, HostFSDump, 2, VMnix_FSDumpArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FileCreate, HostFileCreate, 2, VMnix_FileCreateArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(COWOpenHierarchy, HostCOWOpenHierarchy, 3, VMnix_COWOpenHierarchyArgs *, args, VMnix_COWOpenHierarchyResult *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(COWCombine, HostCOWCombine, 2, VMnix_COWCombineArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(COWGetBlockNumberAndFID, HostCOWGetBlockNumberAndFID, 3, VMnix_COWGetFIDAndLBNArgs *, args, VMnix_COWGetFIDAndLBNResult *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(COWCloseHierarchy, HostCOWCloseHierarchy, 2, COW_HandleID *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(VSCSICreateDev, HostVSCSICreateDev, 3, VMnix_VSCSICreateDevArgs *, hostArgs, VMnix_VSCSICreateDevResult *, hostResult, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(VSCSIDestroyDev, HostVSCSIDestroyDev, 2, VMnix_VSCSIDestroyDevArgs *, hostArgs, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(MapRawDisk, HostMapRawDisk, 2, VMnix_MapRawDiskArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(QueryRawDisk, HostQueryRawDisk, 3, VMnix_QueryRawDiskArgs *, args, VMnix_QueryRawDiskResult *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FileAttr, HostFileAttr, 3, VMnix_FileAttrArgs *, args, VMnix_FileAttrResult *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FileSetAttr, HostFileSetAttr, 2, VMnix_FileSetAttrArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FileIO, HostFileIO, 2, VMnix_FileIOArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FileRemove, HostFileRemove, 2, VMnix_FileRemoveArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FileRename, HostFileRename, 2, VMnix_FileRenameArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(LUNReserve, HostLUNReserve, 2, VMnix_LUNReserveArgs *, args, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(MarkCheckpoint, HostMarkCheckpoint, 2, VMnix_MarkCheckpointArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(SetDumpPartition, HostSetDumpPartition, 2, VMnix_SetDumpArgs *, hostArgs, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(ActivateSwapFile, HostActivateSwapFile, 2, VMnix_ActivateSwapFileArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(DeactivateSwapFile, HostDeactivateSwapFile, 2, uint32 *, ndx, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(ReadCptData, HostMigrateReadCptData, 3, VMnix_MigCptDataArgs *, args, void *, data, uint32, outBufferLength)
VMNIX_VMK_CALL(WriteCptData, HostMigrateWriteCptData, 2, VMnix_MigCptDataArgs *, args, void *, hostBuf)
VMNIX_VMK_CALL(DelaySCSICmds, HostDelaySCSICmds, 2, World_ID, worldID, uint32, delay)
VMNIX_VMK_CALL(GetNextAnonPage, HostGetNextAnonPage, 3, World_ID, worldID, MPN, inMPN, VMnix_GetNextAnonPageResult *, result)
VMNIX_VMK_CALL(GetMPNContents, Alloc_GetMPNContents, 2, MPN, mpn, char *, data)
VMNIX_VMK_CALL(ReadVMKStack, HostReadVMKStack, 4, World_ID, worldID, int, pageNum, char *, pageBuffer, VA *, vAddr)
VMNIX_VMK_CALL(ScanAdapter, HostScanAdapter, 2, VMnix_ScanAdapterArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(HotAddMemory, Init_PostBootMemory, 1, VMnix_HotAddMemory *, args)
VMNIX_VMK_CALL(MigrateToBegin, HostMigrateToBegin, 2, void *, wPtr, VMnix_MigrateProgressResult *, progress)
VMNIX_VMK_CALL(MigrateCheckProgress, Migrate_CheckProgress, 2, VMnix_MigrateProgressArgs *, args, VMnix_MigrateProgressResult *, progress)
VMNIX_VMK_CALL(GetActiveVMCount, World_ActiveGroupCount, 0)
VMNIX_VMK_CALL(ReadVMKCoreMem, HostReadVMKCoreMem, 3, VA, vaddr, uint32, len, char *, buffer)
VMNIX_VMK_CALL(CopyToCOS, HostCopyToCOS, 3, char*, cosAddr, const char*, vmkAddr, uint32, len)
VMNIX_VMK_CALL(CopyFromCOS, HostCopyFromCOS, 3, char*, vmkAddr, const char*, cosAddr, uint32, len)
VMNIX_VMK_CALL(InitVMKernel, InitVMKernel, 1, VMnix_InitArgs *, initArgs)
VMNIX_VMK_CALL(GetSysInfoOld, VSI_GetInfoOld, 3, void *, inBuf, void *, outBuf, int, outBufLen)
VMNIX_VMK_CALL(SysInfoGet, VSI_GetInfo, 3, void *, info, void *, outBuf, int, outBufLen)
VMNIX_VMK_CALL(SysInfoSet, VSI_SetInfo, 2, void *, info, void *, inputArgs)
VMNIX_VMK_CALL(SysInfoGetList, VSI_GetList, 3, void *, info, void *, outBuf, int, outBufLen)
VMNIX_VMK_CALL(GetNicState, HostGetNicState, 2, char *, nicName, VMnix_CosVmnicInfo *, vmnicInfo)
VMNIX_VMK_CALL(SetCOSContext, HostSetCOSContext, 1, VMnix_SetCOSContextArgs*, args)
VMNIX_VMK_CALL(GetTimeOfDay, HostGetTimeOfDay, 1, int64 *, usec)
VMNIX_VMK_CALL(CheckDevName, PCI_CheckDevName, 1, VMnix_DevArgs *, args)
VMNIX_VMK_CALL(CosPanic, HostCosPanic, 1, VMnix_CosPanicArgs *, args)
VMNIX_VMK_CALL(FileGetPhysLayout, HostFileGetPhysLayout, 3, VMnix_FileGetPhysLayoutArgs *, args, VMnix_FileGetPhysLayoutResult *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(SCSIAdapterList, HostSCSIAdapterList, 3, VMnix_AdapterListArgs *, args, VMnix_AdapterListResult *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(GetLUNList, HostGetLUNList, 3, VMnix_LUNListArgs *, args, VMnix_LUNListResult *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(CreateConduitAdapter, HostCreateConduitAdapter, 2, VMnix_CreateConduitAdapArgs *, args, VMnix_CreateConduitAdapResult *, result)
VMNIX_VMK_CALL(RemoveConduitAdapter, HostRemoveConduitAdapter, 1, VMnix_RemoveConduitAdapArgs *, hostArgs)
VMNIX_VMK_CALL(ConduitTransmit, HostConduitTransmit, 1, Conduit_HandleID *, handleID)
VMNIX_VMK_CALL(GetConduitVersion, HostGetConduitVersion, 1, Conduit_HandleID *, handleID)
VMNIX_VMK_CALL(ConduitVDevInfo, HostConduitVDevInfo, 2, VMnix_ConduitDevInfoArgs *, args, CnDev_Record *, rec)
VMNIX_VMK_CALL(ConduitConfigDevForWorld, HostConduitConfigDevForWorld, 1, VMnix_ConduitConfigDevForWorldArgs *, args)
VMNIX_VMK_CALL(ConduitGetBackingStore, HostConduitGetBackingStore, 3, Conduit_HandleID, handleID, uint32, pgNum, MPN *, allocMPN)
VMNIX_VMK_CALL(ConduitEnable, HostConduitEnable, 4, Conduit_HandleID, handleID, World_ID, worldID, Conduit_HandleEnableArgs *, enableArgs, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(ConduitDisable, HostConduitDisable, 1, Conduit_HandleID *, handleID)
VMNIX_VMK_CALL(ConduitDeviceMemory, HostConduitDeviceMemory, 2, VMnix_ConduitDeviceMemoryArgs *, args, Conduit_DeviceMemoryCmd *, result)
VMNIX_VMK_CALL(ConduitRemovePipe, HostConduitRemovePipe, 1, VMnix_ConduitRemovePipeArgs *, hostArgs)
VMNIX_VMK_CALL(ConduitNewPipe, HostConduitNewPipe, 2, VMnix_ConduitNewPipeArgs *, hostOpenArgs, Conduit_OpenPipeArgs *, result)
VMNIX_VMK_CALL(ConduitSend, HostConduitSend, 2, World_ID, worldID, Conduit_HandleID, handleID)
VMNIX_VMK_CALL(ConduitLockPage, HostConduitLockPage, 2, VMnix_ConduitLockPageArgs *, hostArgs, uint32 *, result)
VMNIX_VMK_CALL(AllocLowVMKPages, HostAllocLowVMKPages, 2, MPN *, mpn, uint32, pages)
VMNIX_VMK_CALL(FreeLowVMKPages, HostFreeLowVMKPages, 1, MPN, mpn)
VMNIX_VMK_CALL(AddCOSLUNs, SCSI_AddCOSLunList, 4, uint16, bus, uint16, devfn, uint32 *, tgtLuns, uint16, numLuns)
VMNIX_VMK_CALL(FDSMakeDev, HostFDSMakeDev, 2, VMnix_FDS_MakeDevArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(ForwardKeyFromHost, Keyboard_ForwardKeyFromHost, 1, char, c)
VMNIX_VMK_CALL(FDSOpenDev, HostFDSOpenDev, 3, VMnix_FDS_OpenDevArgs *, args, VMnix_FDS_OpenDevResult *, result, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FDSCloseDev, HostFDSCloseDev, 2, VMnix_FDS_CloseDevArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FDSIO, HostFDSIO, 2, VMnix_FDS_IOArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FDSIoctl, HostFDSIoctl, 2, VMnix_FDS_IoctlArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(FileLookup, HostFileLookup, 3, VMnix_FileLookupArgs *, args, VMnix_FileLookupResult *, result, Helper_RequestHandle *, hostHelperHandle)
VMNIX_VMK_CALL(ProxyObjReady, Host_UserProxyObjReady, 2, VMnix_ProxyObjReadyArgs *, args, Helper_RequestHandle *, helperHandle)
VMNIX_VMK_CALL(AddEnvVar, Host_UserAddEnvVar, 1, VMnix_AddEnvVarArgs *, args)

/*
 * VMK_VMX_PASSTHROUGH calls currently can have a max of 3 parameters passed to
 * them
 *    handlerFn(void *inData, void *outData, uint32 outDataLen)
 */
#ifndef VMX_VMK_PASSTHROUGH
#define VMX_VMK_PASSTHROUGH(...)
#endif
VMX_VMK_PASSTHROUGH(INIT_MIGRATION, HostMigrateSetParameters)
VMX_VMK_PASSTHROUGH(SAVE_MEMORY, HostSaveMemory)
VMX_VMK_PASSTHROUGH(SET_VMX_INFO, World_SetVMXInfo)
VMX_VMK_PASSTHROUGH(CHECKPOINT_CLEANUP, HostCheckpointCleanup)
VMX_VMK_PASSTHROUGH(SET_DEV_NAME, PCI_SetDevName)
VMX_VMK_PASSTHROUGH(SCAN_DEV, PCI_ScanDev)
VMX_VMK_PASSTHROUGH(SYSINFO_SET_OLD, VSI_SetInfoOld)
VMX_VMK_PASSTHROUGH(SET_TIME_OF_DAY, HostSetTimeOfDay)
VMX_VMK_PASSTHROUGH(RUN_WORLD, Host_RunWorld)
VMX_VMK_PASSTHROUGH(ADD_WORLD_ARG, Host_UserAddArg)
VMX_VMK_PASSTHROUGH(CHECK_ACTIONS, HostCheckActions)
VMX_VMK_PASSTHROUGH(MEM_MAP, HostMemMap)
VMX_VMK_PASSTHROUGH(SHARED_AREA_MAP, SharedArea_Map)
VMX_VMK_PASSTHROUGH(SET_MMAP_LAST, HostSetMemMapLast)
VMX_VMK_PASSTHROUGH(SET_MPN_CONTENTS, Alloc_SetMPNContents)
VMX_VMK_PASSTHROUGH(BREAK_INTO_USERWORLD, UserDebug_WantBreakpoint)
VMX_VMK_PASSTHROUGH(SET_BREAK, Host_UserSetBreak)
VMX_VMK_PASSTHROUGH(SET_LOADER_INFO, Host_UserSetLoaderInfo)
VMX_VMK_PASSTHROUGH(CARTEL_FWDSIGNAL, Host_UserForwardSignal)
VMX_VMK_PASSTHROUGH(SET_WORLD_WD, Host_UserSetWorldWD)
VMX_VMK_PASSTHROUGH(USER_MAP_FILE, Host_UserMapFile)
VMX_VMK_PASSTHROUGH(USER_MAP_SECTION, Host_UserMapSection)
VMX_VMK_PASSTHROUGH(SET_WORLD_IDENTITY, Host_UserSetIdentity)
VMX_VMK_PASSTHROUGH(SET_WORLD_DUMPFLAG, Host_UserSetDumpFlag)
VMX_VMK_PASSTHROUGH(SET_MAX_ENV_VARS, Host_UserSetMaxEnvVars)
VMX_VMK_PASSTHROUGH(SET_EXEC_NAME, HostUserSetExecName)
VMX_VMK_PASSTHROUGH(CREATE_SPECIAL_FDS, Host_UserCreateSpecialFds)
VMX_VMK_PASSTHROUGH(DISABLE_CONDUIT, HostConduitDisable)
VMX_VMK_PASSTHROUGH(CONDUIT_DEVICE_MEMORY, HostConduitDeviceMemory)
VMX_VMK_PASSTHROUGH(CONDUIT_NEW_PIPE, HostConduitNewPipe)
VMX_VMK_PASSTHROUGH(CONDUIT_REMOVE_PIPE, HostConduitRemovePipe)
VMX_VMK_PASSTHROUGH(CONDUIT_LOCK_PAGE, HostConduitLockPage)
VMX_VMK_PASSTHROUGH(CONDUIT_VDEV_INFO, HostConduitVDevInfo)
VMX_VMK_PASSTHROUGH(CREATE_CONDUIT_ADAPTER, HostCreateConduitAdapter)
VMX_VMK_PASSTHROUGH(CLOSE_CONDUIT, HostRemoveConduitAdapter)
VMX_VMK_PASSTHROUGH(SET_COS_PID, HostUserSetCosPid)
#undef VMX_VMK_PASSTHROUGH

#undef VMNIX_VMK_CALL
