/* **********************************************************
 * Copyright 2003 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

/*
 * Table of system calls, to be included as needed (typically twice:
 * for the enum declaration, and for a string table for printing).
 *
 * Note:  When you add a new syscall or change an existing one, make
 * sure to update the version number in vmnix_syscall_dist.h.  Also
 * update the version if you change the order of calls in the list 
 * below.
 *
 * Usage: VMX_VMNIX_CALL(syscall name, handler name, vmk loaded?)
 *    syscall name:  name of the syscall.  VMNIX_ will automaticaly
 *                   be prepended
 *    handler name: Name of handler function in vmnix/module.c
 *    vmk loaded:   Does the vmkernel need to be loaded for this
 *                  system call to succeed.
 *
 * For syscalls that are not implemented in module.c, use the
 * VMX_VMNIX_EXTERN_CALL macro.
 *
 * The system calls listed below are those referenced only by our 
 * private (aka non-gpled) source code.
 */

#ifndef VMX_VMNIX_EXTERN_CALL
#define VMX_VMNIX_EXTERN_CALL VMX_VMNIX_CALL
#endif


//vmx->vmnix calls which don't require the vmkernel to be loaded
VMX_VMNIX_CALL(UNLOAD_CMD, UnloadVMKernel, VMKERNEL_NOT_REQUIRED)   // does own checking
VMX_VMNIX_CALL(LOAD_CMD, LoadVMKernel, VMKERNEL_NOT_REQUIRED)
VMX_VMNIX_CALL(ALLOW_COREDUMP, VMnixAllowCoreDump, VMKERNEL_NOT_REQUIRED)
VMX_VMNIX_CALL(LIVE_COREDUMP, VMnixLiveCoreDump, VMKERNEL_NOT_REQUIRED)
VMX_VMNIX_CALL(GET_LOG_MESSAGES, GetLogMessages, VMKERNEL_NOT_REQUIRED)
VMX_VMNIX_CALL(SETUID, devel_suid, VMKERNEL_NOT_REQUIRED)
VMX_VMNIX_CALL(CH_DEV_OWNER, ChDevOwner, VMKERNEL_NOT_REQUIRED)
VMX_VMNIX_CALL(GET_DEV_INFO, GetDevInfo, VMKERNEL_NOT_REQUIRED)

//vmx->vmnix calls which require the vmkernel to be loaded
VMX_VMNIX_CALL(GETCPUKHZ, GetCPUKhzEstimate, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(NUM_CPUS_USED, GetNumCPUsUsed, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(LOGICAL_PER_PACKAGE, GetNumLogicalPerPackage, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(READ_PAGE_CMD, ReadPage, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(READ_REGS_CMD, ReadRegs, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(GET_APIC_BASE, GetAPICBase, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(NET_CONNECT, NetConnect, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(NET_DISCONNECT, NetDisconnect, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(OPEN_SERIAL_PORT, OpenSerialPort, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(FS_CREATE, VMFS_Create, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(FS_TOVMFS2, VMFS_ToVMFS2, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(FS_EXTEND, VMFS_Extend, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(FS_SET_ATTR, VMFS_SetAttr, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(FS_DUMP, VMFS_Dump, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(FILE_RESERVE, VMFS_FileReserve, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(MARK_CHECKPOINT, MarkCheckpoint, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(SET_DUMP_PARTITION, SetDumpPartition, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(GET_DUMP_PARTITION, GetDumpPartition, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(ADD_PAGE_CMD, AddPage, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(READ_CPT_DATA, ReadCptData, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(WRITE_CPT_DATA, WriteCptData, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(DELAY_SCSI_CMDS, DelaySCSICmds, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(WAIT_WORLD_REAP, VMnixWaitForWorldReap, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(LOOKUP_MPN_CMD, LookupMPN, VMKERNEL_NOT_REQUIRED)
VMX_VMNIX_EXTERN_CALL(MAP_RAWDISK, VMFS_MapRawDisk, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(QUERY_RAWDISK, VMFS_QueryRawDisk, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(ACTIVATE_SWAP_FILE, VMFSActivateSwapFile, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(DEACTIVATE_SWAP_FILE, VMFSDeactivateSwapFile, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(GET_NEXT_ANON_PAGE, GetNextAnonPage, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(GET_MPN_CONTENTS, GetMPNContents, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(READ_VMKSTACK_CMD, ReadVMKStack, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(SCAN_ADAPTER, ScanAdapter, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(GET_CPUIDS, GetCPUIDs, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(HOT_ADD_MEMORY, HotAddMemory, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(POLL_FOR_MIG_DATA, MigratePollForData, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(MIG_CHECK_PROGRESS, MigrateCheckProgress, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(SYSINFO_GET_OLD, VmnixSysInfoGetInfoOld, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(SYSINFO_GET, VmnixSysInfoGetInfo, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(SYSINFO_SET, VmnixSysInfoSetInfo, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(SYSINFO_GETLIST, VmnixSysInfoGetList, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(NUM_RUNNING_VMS, VMnixRunningVMs, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(GET_TIME_OF_DAY, GetTimeOfDay, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(CREATE_USER_WORLD, CreateUserWorld, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(SCSI_ADAPTER_LIST, SCSIAdapterList, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(LUN_LIST, GetLUNList, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(ENABLE_CONDUIT, VMXConduitEnable, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(CONDUIT_CONFIG_DEV_FOR_WORLD, ConduitConfigDevForWorld, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(CONDUIT_SEND, ConduitSend, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(COW_OPEN_HIERARCHY, COWOpenHierarchy, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(COW_COMBINE, COWCombine, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(COW_GET_BLOCKNUMBER_AND_FID, COWGetBlockNumberAndFID, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(COW_CLOSE_HIERARCHY, COWCloseHierarchy, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(MAKE_FSDEV, VMFS_MakeDevWrapper, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(VSCSI_CREATE_DEV, VSCSICreateDev, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(VSCSI_DESTROY_DEV, VSCSIDestroyDev, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(PROXY_OBJ_READY, ProxyObjReady, VMKERNEL_REQUIRED)
VMX_VMNIX_EXTERN_CALL(FILE_GET_PHYSLAYOUT, VMFS_FileGetPhysLayout, VMKERNEL_REQUIRED)
VMX_VMNIX_CALL(ADD_ENV_VAR, AddEnvVar, VMKERNEL_REQUIRED)


//vmx->vmk passthrough calls
#define VMNIX_VMK_CALL(...)
#define VMX_VMK_PASSTHROUGH(_num, _fn) VMX_VMNIX_CALL(_num, _passthrough_##_fn, VMKERNEL_REQUIRED)
#include  "vmk_sctable.h"
#undef VMNIX_VMK_CALL

VMX_VMNIX_CALL(NUM_SYSCALLS, InvalidSyscall, VMKERNEL_NOT_REQUIRED) // must be last

#undef VMX_VMNIX_CALL
#undef VMX_VMNIX_EXTERN_CALL
