/* **********************************************************
 * Copyright 2003 VMware, Inc.  All rights reserved. -- VMware Confidential
 * **********************************************************/

/*
 * compatErrno.h -
 * 	Linux and FreeBSD errno's as defined by FreeBSD --- the actual
 * 	list of generated defines was generated by Pat's errnohack-c.
 *
 * 	The LINUX_* codes are already negated.
 */

/*
 * Contains code generated from code which had LICENSE A and
 * other code which had LICENSE B.  The "adversiting clause"
 * in LICENSE B has been retroactivley deleted. (see:
 *     ftp://ftp.cs.berkeley.edu/pub/4bsd/README.Impt.License.Change
 * ). 
 *
 * LICENSE A:
 * Copyright 1994-2003 FreeBSD, Inc. All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 *    1. Redistributions of source code must retain the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer.
 *    2. Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer in the documentation and/or other materials
 *       provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE FREEBSD PROJECT ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE FREEBSD PROJECT OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 * 
 * The views and conclusions contained in the software and
 * documentation are those of the authors and should not be
 * interpreted as representing official policies, either expressed or
 * implied, of the FreeBSD Project or FreeBSD, Inc.
 *
 *
 * LICENSE B:
 *
 * FreeBSD5.0 linux syscalls.master:
 *      $FreeBSD: src/sys/i386/linux/syscalls.master,v 1.48 2002/09/24 07:03:01 mini Exp $
 *       @(#)syscalls.master     8.1 (Berkeley) 7/19/93
 * 
 * FreeBSD5.0 errno.h:
 *
 * Copyright (c) 1982, 1986, 1989, 1993
 *      The Regents of the University of California.  All rights reserved.
 * (c) UNIX System Laboratories, Inc.
 * All or some portions of this file are derived from material licensed
 * to the University of California by American Telephone and Telegraph
 * Co. or Unix System Laboratories, Inc. and are reproduced herein with
 * the permission of UNIX System Laboratories, Inc.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *      This product includes software developed by the University of
 *      California, Berkeley and its contributors.
 * 4. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 *      @(#)errno.h     8.5 (Berkeley) 1/21/94
 * $FreeBSD: src/sys/sys/errno.h,v 1.25 2002/10/07 06:25:23 phk Exp $
 * 
 */

#ifndef VMKERNEL_USER_COMPATERRNO_H
#define VMKERNEL_USER_COMPATERRNO_H

#define INCLUDE_ALLOW_VMKERNEL
#include "includeCheck.h"

#define   LINUX_EPERM	-1
#define FREEBSD_EPERM	1
#define   LINUX_ENOENT	-2
#define FREEBSD_ENOENT	2
#define   LINUX_ESRCH	-3
#define FREEBSD_ESRCH	3
#define   LINUX_EINTR	-4
#define FREEBSD_EINTR	4
#define   LINUX_EIO	-5
#define FREEBSD_EIO	5
#define   LINUX_ENXIO	-6
#define FREEBSD_ENXIO	6
#define   LINUX_E2BIG	-7
#define FREEBSD_E2BIG	7
#define   LINUX_ENOEXEC	-8
#define FREEBSD_ENOEXEC	8
#define   LINUX_EBADF	-9
#define FREEBSD_EBADF	9
#define   LINUX_ECHILD	-10
#define FREEBSD_ECHILD	10
#define   LINUX_EDEADLK	-35
#define FREEBSD_EDEADLK	11
#define   LINUX_ENOMEM	-12
#define FREEBSD_ENOMEM	12
#define   LINUX_EACCES	-13
#define FREEBSD_EACCES	13
#define   LINUX_EFAULT	-14
#define FREEBSD_EFAULT	14
#define   LINUX_ENOTBLK	-15
#define FREEBSD_ENOTBLK	15
#define   LINUX_EBUSY	-16
#define FREEBSD_EBUSY	16
#define   LINUX_EEXIST	-17
#define FREEBSD_EEXIST	17
#define   LINUX_EXDEV	-18
#define FREEBSD_EXDEV	18
#define   LINUX_ENODEV	-19
#define FREEBSD_ENODEV	19
#define   LINUX_ENOTDIR	-20
#define FREEBSD_ENOTDIR	20
#define   LINUX_EISDIR	-21
#define FREEBSD_EISDIR	21
#define   LINUX_EINVAL	-22
#define FREEBSD_EINVAL	22
#define   LINUX_ENFILE	-23
#define FREEBSD_ENFILE	23
#define   LINUX_EMFILE	-24
#define FREEBSD_EMFILE	24
#define   LINUX_ENOTTY	-25
#define FREEBSD_ENOTTY	25
#define   LINUX_ETXTBSY	-26
#define FREEBSD_ETXTBSY	26
#define   LINUX_EFBIG	-27
#define FREEBSD_EFBIG	27
#define   LINUX_ENOSPC	-28
#define FREEBSD_ENOSPC	28
#define   LINUX_ESPIPE	-29
#define FREEBSD_ESPIPE	29
#define   LINUX_EROFS	-30
#define FREEBSD_EROFS	30
#define   LINUX_EMLINK	-31
#define FREEBSD_EMLINK	31
#define   LINUX_EPIPE	-32
#define FREEBSD_EPIPE	32
#define   LINUX_EDOM	-33
#define FREEBSD_EDOM	33
#define   LINUX_ERANGE	-34
#define FREEBSD_ERANGE	34
#define   LINUX_EAGAIN	-11
#define FREEBSD_EAGAIN	35
#define   LINUX_EWOULDBLOCK	-35
#define FREEBSD_EWOULDBLOCK	11
#define   LINUX_EINPROGRESS	-115
#define FREEBSD_EINPROGRESS	36
#define   LINUX_EALREADY	-114
#define FREEBSD_EALREADY	37
#define   LINUX_ENOTSOCK	-88
#define FREEBSD_ENOTSOCK	38
#define   LINUX_EDESTADDRREQ	-89
#define FREEBSD_EDESTADDRREQ	39
#define   LINUX_EMSGSIZE	-90
#define FREEBSD_EMSGSIZE	40
#define   LINUX_EPROTOTYPE	-91
#define FREEBSD_EPROTOTYPE	41
#define   LINUX_ENOPROTOOPT	-92
#define FREEBSD_ENOPROTOOPT	42
#define   LINUX_EPROTONOSUPPORT	-93
#define FREEBSD_EPROTONOSUPPORT	43
#define   LINUX_ESOCKTNOSUPPORT	-94
#define FREEBSD_ESOCKTNOSUPPORT	44
#define   LINUX_EOPNOTSUPP	-95
#define FREEBSD_EOPNOTSUPP	45
#define   LINUX_EPFNOSUPPORT	-96
#define FREEBSD_EPFNOSUPPORT	46
#define   LINUX_EAFNOSUPPORT	-97
#define FREEBSD_EAFNOSUPPORT	47
#define   LINUX_EADDRINUSE	-98
#define FREEBSD_EADDRINUSE	48
#define   LINUX_EADDRNOTAVAIL	-99
#define FREEBSD_EADDRNOTAVAIL	49
#define   LINUX_ENETDOWN	-100
#define FREEBSD_ENETDOWN	50
#define   LINUX_ENETUNREACH	-101
#define FREEBSD_ENETUNREACH	51
#define   LINUX_ENETRESET	-102
#define FREEBSD_ENETRESET	52
#define   LINUX_ECONNABORTED	-103
#define FREEBSD_ECONNABORTED	53
#define   LINUX_ECONNRESET	-104
#define FREEBSD_ECONNRESET	54
#define   LINUX_ENOBUFS	-105
#define FREEBSD_ENOBUFS	55
#define   LINUX_EISCONN	-106
#define FREEBSD_EISCONN	56
#define   LINUX_ENOTCONN	-107
#define FREEBSD_ENOTCONN	57
#define   LINUX_ESHUTDOWN	-108
#define FREEBSD_ESHUTDOWN	58
#define   LINUX_ETOOMANYREFS	-109
#define FREEBSD_ETOOMANYREFS	59
#define   LINUX_ETIMEDOUT	-110
#define FREEBSD_ETIMEDOUT	60
#define   LINUX_ECONNREFUSED	-111
#define FREEBSD_ECONNREFUSED	61
#define   LINUX_ELOOP	-40
#define FREEBSD_ELOOP	62
#define   LINUX_ENAMETOOLONG	-36
#define FREEBSD_ENAMETOOLONG	63
#define   LINUX_EHOSTDOWN	-112
#define FREEBSD_EHOSTDOWN	64
#define   LINUX_EHOSTUNREACH	-113
#define FREEBSD_EHOSTUNREACH	65
#define   LINUX_ENOTEMPTY	-39
#define FREEBSD_ENOTEMPTY	66
//#define   LINUX_EPROCLIM	// no equivalent in linux
#define FREEBSD_EPROCLIM	67
#define   LINUX_EUSERS	-87
#define FREEBSD_EUSERS	68
#define   LINUX_EDQUOT	-122
#define FREEBSD_EDQUOT	69
#define   LINUX_ESTALE	-116
#define FREEBSD_ESTALE	70
#define   LINUX_EREMOTE	-66
#define FREEBSD_EREMOTE	71
#define   LINUX_EBADRPC	-6
#define FREEBSD_EBADRPC	72
#define   LINUX_ERPCMISMATCH	-6
#define FREEBSD_ERPCMISMATCH	73
#define   LINUX_EPROGUNAVAIL	-6
#define FREEBSD_EPROGUNAVAIL	74
#define   LINUX_EPROGMISMATCH	-6
#define FREEBSD_EPROGMISMATCH	75
#define   LINUX_EPROCUNAVAIL	-6
#define FREEBSD_EPROCUNAVAIL	76
#define   LINUX_ENOLCK	-37
#define FREEBSD_ENOLCK	77
#define   LINUX_ENOSYS	-38
#define FREEBSD_ENOSYS	78
#define   LINUX_EFTYPE	-9
#define FREEBSD_EFTYPE	79
#define   LINUX_EAUTH	-6
#define FREEBSD_EAUTH	80
#define   LINUX_ENEEDAUTH	-6
#define FREEBSD_ENEEDAUTH	81
#define   LINUX_EIDRM	-43
#define FREEBSD_EIDRM	82
#define   LINUX_ENOMSG	-42
#define FREEBSD_ENOMSG	83
#define   LINUX_EOVERFLOW	-75
#define FREEBSD_EOVERFLOW	84
#define   LINUX_ECANCELED	-6
#define FREEBSD_ECANCELED	85
#define   LINUX_EILSEQ	-84
#define FREEBSD_EILSEQ	86
//#define   LINUX_ENOATTR	0
#define FREEBSD_ENOATTR	87
//#define   LINUX_EDOOFUS	0
#define FREEBSD_EDOOFUS	88

#define LINUX_ERESTARTSYS -512

/*
 * Linux is limited to 4096 errno codes.
 */
#define LINUX_ERRNO_MAX  -4096

#endif /* VMKERNEL_USER_COMPATERRNO_H */
